# Generated by Django 3.1.5 on 2021-06-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Farmer', models.CharField(max_length=250)),
                ('Farmer_location', models.CharField(max_length=500)),
                ('Farmer_speciality', models.CharField(max_length=600)),
                ('Farmer_contact', models.IntegerField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Contact', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
    ]
