# Generated by Django 3.1.5 on 2021-06-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='Farmer_contact',
            field=models.CharField(max_length=500),
        ),
    ]
