# Generated by Django 3.1.5 on 2021-06-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0002_auto_20210603_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='Farmer',
            new_name='Jina',
        ),
    ]
