# Generated by Django 3.1.5 on 2021-06-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0003_auto_20210603_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='Farmer_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='Farmer_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='Farmer_speciality',
            new_name='specialization',
        ),
    ]
