# Generated by Django 3.1.5 on 2021-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0005_farmer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='logo',
            field=models.FileField(default='/logo.png', upload_to='logos'),
        ),
    ]
